"""
Outcome simulation (Monte Carlo) + PineScript strategy generator.

monte_carlo: projects a range of possible future prices from historical
daily returns (geometric Brownian motion). This is a statistical "what could
happen" spread — NOT a prediction. Past volatility/drift rarely repeats.

generate_pinescript: emits a TradingView Pine v5 strategy that mirrors the
app's technical signals (SMA200 trend + MACD + RSI), so you can backtest the
"possibilities of the outcomes" on TradingView's historical data.
"""
import numpy as np
import pandas as pd


def monte_carlo(df: pd.DataFrame, days: int = 10, n_sims: int = 2000,
                seed: int | None = 42) -> dict:
    """
    Returns a dict with the distribution of simulated end prices over `days`:
        current, median_end, p10, p90, prob_up, exp_return_pct, bands(DataFrame)
    `bands` holds per-day p10/p50/p90 price paths for charting. {} if no data.
    """
    if df is None or df.empty or "Close" not in df.columns:
        return {}
    close = df["Close"].dropna()
    if len(close) < 30:
        return {}

    rng = np.random.default_rng(seed)
    log_ret = np.log(close / close.shift(1)).dropna()
    mu = float(log_ret.mean())
    sigma = float(log_ret.std())
    s0 = float(close.iloc[-1])

    # simulate daily shocks: shape (days, n_sims)
    shocks = rng.normal(mu, sigma, size=(days, n_sims))
    paths = s0 * np.exp(np.cumsum(shocks, axis=0))

    end = paths[-1, :]
    p10_path = np.percentile(paths, 10, axis=1)
    p50_path = np.percentile(paths, 50, axis=1)
    p90_path = np.percentile(paths, 90, axis=1)

    bands = pd.DataFrame({
        "day": np.arange(1, days + 1),
        "p10": p10_path, "p50": p50_path, "p90": p90_path,
    })

    return {
        "current": round(s0, 2),
        "median_end": round(float(np.median(end)), 2),
        "p10": round(float(np.percentile(end, 10)), 2),
        "p90": round(float(np.percentile(end, 90)), 2),
        "prob_up": round(float((end > s0).mean()) * 100, 1),
        "exp_return_pct": round((float(np.median(end)) - s0) / s0 * 100, 2),
        "days": days,
        "n_sims": n_sims,
        "bands": bands,
    }


def generate_pinescript(symbol: str = "TICKER") -> str:
    """Pine v5 strategy mirroring the app's technical signals, for TradingView backtesting."""
    return f'''//@version=5
// Auto-generated by the Kronos dashboard — technical-signal strategy for {symbol}.
// Paste into TradingView (Pine Editor) -> Add to chart -> Strategy Tester to
// backtest the range of possible outcomes on real historical data.
strategy("Kronos Signals — {symbol}", overlay=true,
     initial_capital=100000, default_qty_type=strategy.percent_of_equity,
     default_qty_value=100, commission_type=strategy.commission.percent,
     commission_value=0.05)

// ---- Inputs ----
rsiLen   = input.int(14,  "RSI Length")
rsiBuy   = input.int(50,  "RSI bull floor")
rsiOB    = input.int(70,  "RSI overbought")
fastLen  = input.int(12,  "MACD fast")
slowLen  = input.int(26,  "MACD slow")
sigLen   = input.int(9,   "MACD signal")
trendLen = input.int(200, "Trend SMA")

// ---- Indicators (mirror compute_technical_score) ----
rsi = ta.rsi(close, rsiLen)
[macdLine, signalLine, _] = ta.macd(close, fastLen, slowLen, sigLen)
sma50  = ta.sma(close, 50)
sma200 = ta.sma(close, trendLen)

// ---- Signal logic ----
bull = close > sma200 and macdLine > signalLine and rsi > rsiBuy and rsi < rsiOB
bear = close < sma200 and macdLine < signalLine and rsi < rsiBuy

if bull
    strategy.entry("Long", strategy.long)
if bear
    strategy.close("Long")

// ---- Plots ----
plot(sma50,  "SMA 50",  color=color.new(color.aqua, 0))
plot(sma200, "SMA 200", color=color.new(color.orange, 0))
bgcolor(bull ? color.new(color.green, 88) : bear ? color.new(color.red, 88) : na)
'''
